// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using villaroom_API.Data;

#nullable disable

namespace villaroom_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250129021705_AlimentarTablaVilla")]
    partial class AlimentarTablaVilla
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("villaroom_API.models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MetrosCuadrado")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ocupantes")
                        .HasColumnType("int");

                    b.Property<double>("Tarifa")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenidad = "Piscina",
                            Detalle = "Dettale Mercedes",
                            FechaActualizacion = new DateTime(2025, 1, 28, 23, 17, 4, 615, DateTimeKind.Local).AddTicks(6096),
                            FechaCreacion = new DateTime(2025, 1, 28, 23, 17, 4, 613, DateTimeKind.Local).AddTicks(9995),
                            ImagenUrl = "image_url",
                            MetrosCuadrado = 120,
                            Name = "Villa Las Mercedes",
                            Ocupantes = 4,
                            Tarifa = 200.0
                        },
                        new
                        {
                            Id = 2,
                            Amenidad = "Gimnasio",
                            Detalle = "Dettale Oasis",
                            FechaActualizacion = new DateTime(2025, 1, 28, 23, 17, 4, 615, DateTimeKind.Local).AddTicks(6297),
                            FechaCreacion = new DateTime(2025, 1, 28, 23, 17, 4, 615, DateTimeKind.Local).AddTicks(6292),
                            ImagenUrl = "image_url",
                            MetrosCuadrado = 150,
                            Name = "Villa El Oasis",
                            Ocupantes = 6,
                            Tarifa = 250.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
